const snippetJson = {
  "snippet": [
    {
      "nodeName": "forloop",
      "data": "{'uid':'🔥🔥🔥','sourceFileId':'','sourceWorkspaceName':'private','nodes':[{'uid':'02dd2fcf-6912-467e-a161-08f0a3808200','commandName':'Comment','packageName':'Comment','disabled':false,'attributes':[{'name':'comment','value':{'type':'STRING','string':'Iterando en ...'}}]},{'uid':'d50db640-69fe-4cb4-bddb-575201e34427','commandName':'assignToNumber','packageName':'Number','disabled':false,'attributes':[{'name':'input','value':{'type':'NUMBER','number':'0'}}],'returnTo':{'type':'VARIABLE','variableName':'pNumCounter'}},{'uid':'2f3bfdc3-cfa8-4623-9d20-7113334c1fbd','commandName':'loop.commands.start','packageName':'Loop','disabled':false,'children':[{'uid':'6388e3f5-600f-43d8-be96-dc7d03b9ebd2','commandName':'increment','packageName':'Number','disabled':false,'attributes':[{'name':'source','value':{'type':'NUMBER','expression':'$pNumCounter$'}},{'name':'by','value':{'type':'NUMBER','number':'1'}}],'returnTo':{'type':'VARIABLE','variableName':'pNumCounter'}}],'attributes':[{'name':'loopType','value':{'type':'STRING','string':'ITERATOR'}},{'name':'iterator','attributes':[{'name':'times','value':{'number':'10','type':'NUMBER'}}],'value':{'type':'ITERATOR','iteratorName':'loop.iterators.times','packageName':'Loop'}}]}],'variables':[{'name':'pNumCounter','description':'','type':'NUMBER','readOnly':false,'input':false,'output':false,'defaultValue':{'type':'NUMBER','number':'0'},'key':'pnumcounter'}],'packages':[{'name':'Comment','version':'2.16.0'},{'name':'Number','version':'3.9.1'},{'name':'Loop','version':'3.8.1-20231117-175130'}]}"
    },
    {
      "nodeName": "comment",
      "data": "{'uid':'🔥🔥🔥','sourceFileId':'','sourceWorkspaceName':'private','nodes':[{'uid':'d5ecd664-4469-4bc0-a6bc-a568810f8c81','commandName':'Comment','packageName':'Comment','disabled':false,'attributes':[{'name':'comment','value':{'type':'STRING','string':'====================='}}]},{'uid':'14f61aa7-1f62-44a9-b249-95943ec1c538','commandName':'Comment','packageName':'Comment','disabled':false,'attributes':[{'name':'comment','value':{'type':'STRING','string':'Creado por 🧠 el 🕐'}}]},{'uid':'a1ffa4ad-8f9c-4c1b-aff2-f0819fc82a4f','commandName':'Comment','packageName':'Comment','disabled':false,'attributes':[{'name':'comment','value':{'type':'STRING','string':'What does this task do?'}}]},{'uid':'be76f326-e03d-4c7c-aeea-86cad2a7aa75','commandName':'Comment','packageName':'Comment','disabled':false,'attributes':[{'name':'comment','value':{'type':'STRING','string':'Parameters:\n    '}}]},{'uid':'b4b53208-d253-4224-aafc-2fae40b6a342','commandName':'Comment','packageName':'Comment','disabled':false,'attributes':[{'name':'comment','value':{'type':'STRING','string':'iDictConfig(dictionary): Diccionario config de la instancia de ejecución'}}]},{'uid':'5c7835b1-22a7-4d9c-b2d4-2584598101c5','commandName':'Comment','packageName':'Comment','disabled':false,'attributes':[{'name':'comment','value':{'type':'STRING','string':'Returns:'}}]},{'uid':'b6df6ce8-24b2-425b-8146-9d08bb428df8','commandName':'Comment','packageName':'Comment','disabled':false,'attributes':[{'name':'comment','value':{'type':'STRING','string':'oStrErrorMessaje(string): Error levantado durante la ejecucion'}}]},{'uid':'85013397-a7fc-4efb-b969-3d8c17547dbe','commandName':'Comment','packageName':'Comment','disabled':false,'attributes':[{'name':'comment','value':{'type':'STRING','string':'====================='}}]}],'variables':[],'packages':[{'name':'Comment','version':'2.16.0'}]}"
    },
    {
      "nodeName": "ifstring",
      "data": "{'uid':'🔥🔥🔥','sourceFileId':'','sourceWorkspaceName':'private','nodes':[{'commandName':'if','packageName':'If','children':[],'branches':[],'uid':'a96e7c03-ef6f-4145-93c4-b8d76ee5e09c','attributes':[{'value':{'type':'CONDITIONAL','conditionalName':'stringVariable','packageName':'String'},'attributes':[{'name':'variable','value':{'type':'STRING','string':''}},{'name':'operator','value':{'type':'STRING','string':'EQ'}},{'name':'value','value':{'type':'STRING','string':''}},{'name':'matchCase','value':{'type':'BOOLEAN','boolean':false}},{'name':'isIgnoreCarriage','value':{'type':'BOOLEAN','boolean':false}}],'name':'condition'}]}],'variables':[],'packages':[{'name':'If','version':'3.7.14-20231116-000453'},{'name':'String','version':'5.9.0'}]}"
    }
  ]
};
